#!/bin/bash
#
# Deletes a Tomcat runtime instance (as created by 'addtomcat85').
#
# Last modified 2017-09-08 by Andrew Taylor
#

# Make sure we are running as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Import default settings
. /etc/default/tomcat85

# Change the variable below to be the user to create.
TOMCAT_USER="$1"

# The 'correct' place for Ubuntu, if not set
if [ -z "${TOMCAT_INSTANCE_BASE}" ] ; then
	TOMCAT_INSTANCE_BASE="/var/lib"
fi

# Instance paths
CONFIG_DIR="/etc/${TOMCAT_USER}"
LOG_DIR="/var/log/${TOMCAT_USER}"
TMP_DIR="/var/tmp/${TOMCAT_USER}"
INIT_SCRIPT="/etc/init.d/${TOMCAT_USER}"
if [ -z "${CATALINA_BASE}" ] ; then
    CATALINA_BASE="${TOMCAT_INSTANCE_BASE}/${TOMCAT_USER}"
fi

if [ -z "${TOMCAT_USER}" ] ; then
    echo "You must specify the instance name as the only argument"
    exit 1
fi

if [ ! -f "${INIT_SCRIPT}" ] ; then
    echo "The instance name '${TOMCAT_USER}' does not appear to exist"
    exit 1
fi

if [ ! -d "${CATALINA_BASE}" ] ; then
    echo "No existing runtime instance found at directory '${CATALINA_BASE}'. Aborting..."
    exit 1
fi

# Last chance to abort.
cat << EOF

You are about to delete the Tomcat 8.5 instance '${TOMCAT_USER}'. This will 
remove the service '${TOMCAT_USER}', delete the user account '${TOMCAT_USER}'
and delete the following directories: 

   ${CONFIG_DIR}
   ${LOG_DIR}
   ${CATALINA_BASE}
   ${TMP_DIR}

If you wish to retain the contents of these folders, then please 
relocate them out of these folders prior to running this command again.

EOF
echo -n "Are you sure you would you like to continue (yes or no)? "
read -e execute_script
if [ "$execute_script" != "yes" ]; then
	echo "User aborted, type 'yes' if you really mean to continue"
	exit 0
fi

# Make sure the service is stopped
service "${TOMCAT_USER}" stop

# Delete the user account
deluser "${TOMCAT_USER}"
if [ "$?" != "0" ] ; then
    echo "The Tomcat runtime instance user '${TOMCAT_USER}' could not be deleted. Aborting..."
    exit 1
fi

# Remove the init.d service script links
INIT_SCRIPT_NAME=`basename "${INIT_SCRIPT}"`
update-rc.d -f "${INIT_SCRIPT_NAME}" remove
# Remove the files / directories
rm "${INIT_SCRIPT}"
rm -Rf "${CONFIG_DIR}" "${LOG_DIR}" "${TMP_DIR}" "${CATALINA_BASE}"

echo "Tomcat 8.5 instance '${TOMCAT_USER}' has been deleted"
